#!/usr/bin/env python
"""Target A / RNAlight — leakage-controlled evaluation, step 1.

Compares LightGBM localization AUROC under:
  (1) random StratifiedKFold      (the leaky baseline)
  (2) sequence-homology GroupKFold (mmseqs linclust cluster = group), id 0.5 & 0.8
  (3) dinucleotide-only composition baseline (random split) — trivial floor
Also quantifies how much sequence-homology actually exists (near-duplicate audit).
"""
# NOTE: np.load(allow_pickle=True) below reads pool_features.npz, which was
# generated by our own prep_pool.py this session (numeric + string arrays only) —
# trusted self-produced file, not external data.
import numpy as np, collections
from sklearn.model_selection import StratifiedKFold, GroupKFold
from sklearn.metrics import roc_auc_score
import lightgbm as lgb

# --- path config: edit these or set env vars. Defaults assume repo layout code/ + data/ ---
import os as _os
_HERE = _os.path.dirname(_os.path.abspath(__file__))
_ROOT = _os.path.dirname(_HERE)
DATA = _os.environ.get('AUDIT_DATA', _os.path.join(_ROOT, 'data'))
FIG  = _os.environ.get('AUDIT_FIGS', _os.path.join(_ROOT, 'figures'))
RNALIGHT_DIR = _os.environ.get('RNALIGHT_DIR', _os.path.join(_ROOT, 'external', 'RNAlight'))
DVMNET_DIR   = _os.environ.get('DVMNET_DIR',   _os.path.join(_ROOT, 'external', 'DVMnet'))
# --- end path config ---
BASE = DATA
SEED = 100
d = np.load(f"{BASE}/pool_features.npz", allow_pickle=True)
X, y, ids, kmers = d["X"], d["y"].astype(int), d["ids"].astype(str), d["kmers"].astype(str)
print(f"[data] X={X.shape} pos={y.sum()} neg={(y==0).sum()}")

def clusters(idv):
    rep = {}
    for line in open(f"{BASE}/mmseqs_clusters/lin_{idv}_cluster.tsv"):
        r, m = line.rstrip("\n").split("\t"); rep[m] = r
    return np.array([rep[i] for i in ids])

def lgbm():
    return lgb.LGBMClassifier(objective="binary", random_state=SEED, n_jobs=-1, verbose=-1)

def cv_auroc(splits):
    aucs = []
    for tr, te in splits:
        m = lgbm().fit(X[tr], y[tr])
        aucs.append(roc_auc_score(y[te], m.predict_proba(X[te])[:, 1]))
    return np.array(aucs)

# (1) random
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
rand = cv_auroc(list(skf.split(X, y)))
print(f"\n(1) RANDOM StratifiedKFold      AUROC = {rand.mean():.4f} ± {rand.std():.4f}   folds={np.round(rand,3)}")

# (2) homology GroupKFold at two identities
for idv in ("05", "08"):
    g = clusters(idv)
    ncl = len(set(g))
    gkf = GroupKFold(n_splits=5)
    hom = cv_auroc(list(gkf.split(X, y, groups=g)))
    print(f"(2) HOMOLOGY GroupKFold id0.{idv[-1]}  AUROC = {hom.mean():.4f} ± {hom.std():.4f}   (groups={ncl})   delta_vs_random={hom.mean()-rand.mean():+.4f}")

# (3) dinucleotide-only composition baseline (random split)
NUC = list("ACGT")
di = ["".join((a,b)) for a in NUC for b in NUC]
# recompute dinucleotide freq from... we only cached 3/4/5-mers; approximate composition floor with 3-mers collapsed is messy.
# Instead: use the 4 mononucleotide-equivalent via summing 3-mers is also messy. Use GC + length-free: fall back to 3-mer-only model as a 'low-order composition' baseline (64 feats) using the cached kmers.
k3_idx = [i for i,k in enumerate(kmers) if len(k)==3]
X3 = X[:, k3_idx]
def cv_auroc_X(Xmat, splits):
    a=[]
    for tr,te in splits:
        m=lgbm().fit(Xmat[tr],y[tr]); a.append(roc_auc_score(y[te],m.predict_proba(Xmat[te])[:,1]))
    return np.array(a)
comp = cv_auroc_X(X3, list(skf.split(X, y)))
print(f"(3) 3-mer-ONLY composition floor (random) AUROC = {comp.mean():.4f} ± {comp.std():.4f}   (64 feats)")

# near-duplicate audit: fraction of seqs that share a multi-seq cluster (i.e., have >=1 homolog in the pool)
for idv in ("05","07","08","09"):
    g = clusters(idv); sizes=collections.Counter(g)
    frac = np.mean([sizes[c]>1 for c in g])
    print(f"[homology audit] id0.{idv[-1]}: {100*frac:.1f}% of lncRNAs have >=1 homolog in the pool (=potential seq-homology leakage surface)")

print("\n[interpretation] If (2) ~= (1), sequence-homology splitting removes ~no leakage because lncRNAs are ~non-homologous;")
print("the RNAlight signal is COMPOSITIONAL, so the honest test must control feature-space composition / study-effort, not BLAST homology.")
